### ISSUE TITLE
when I run /bash build.sh,Is there miss some files?

### ISSUE THREAD

**Issue by wangqi01** [fionser/CODA#1]
In file included from /home/wq/Downloads/CODA-master/core/src/core/algebra/EncVec.cpp:1:0:
/home/wq/Downloads/CODA-master/core/include/core/algebra/EncVec.hpp:4:27: fatal error: core/COWPtr.hpp: no such file or directory
 #include "core/COWPtr.hpp"
                           ^
compilation terminated.

**Comment by fionser** [comment]
sorry,  I will check it.

**Comment by fionser** [comment]
plz try 51fdd8502f2c3563f275265b94402b2da54d7aaa

**Comment by wangqi01** [comment]
I have done this,and installed NTL version 10.3.0, but there are some errors as following:

In file included from /home/wq/Downloads/CODA-master/core/include/HElib/DoubleCRT.h:21:0,
                 from /home/wq/Downloads/CODA-master/core/include/HElib/FHE.h:24,
                 from /home/wq/Downloads/CODA-master/core/include/HElib/EncryptedArray.h:26,
                 from /home/wq/Downloads/CODA-master/core/src/core/algebra/EncMat.cpp:4:
/home/wq/Downloads/CODA-master/core/include/HElib/NumbTh.h:54:2: error: #error "This version of HElib requires NTL version 9.4.0 or above"
 #error "This version of HElib requires NTL version 9.4.0 or above"
  ^
core/src/core-imp/PPE/CMakeFiles/PPE.dir/build.make:77: recipe for target 'core/src/core-imp/PPE/CMakeFiles/PPE.dir/SecKey.cpp.o' failed
make[2]: *** [core/src/core-imp/PPE/CMakeFiles/PPE.dir/SecKey.cpp.o] Error 1
CMakeFiles/Makefile2:335: recipe for target 'core/src/core-imp/PPE/CMakeFiles/PPE.dir/all' failed
make[1]: *** [core/src/core-imp/PPE/CMakeFiles/PPE.dir/all] Error 2
core/src/core-imp/algebra/CMakeFiles/algebra.dir/build.make:77: recipe for target 'core/src/core-imp/algebra/CMakeFiles/algebra.dir/EncMat.cpp.o' failed
make[2]: *** [core/src/core-imp/algebra/CMakeFiles/algebra.dir/EncMat.cpp.o] Error 1
CMakeFiles/Makefile2:285: recipe for target 'core/src/core-imp/algebra/CMakeFiles/algebra.dir/all' failed
make[1]: *** [core/src/core-imp/algebra/CMakeFiles/algebra.dir/all] Error 2
Makefile:85: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by fionser** [comment]
This is a bug of HElib. You can just comment out the codes in "NumbTh.h:54:2"

**Comment by IkarosCoCo** [comment]
Hello, I followed your suggestions,and I meet this new error:

[ 66%] Building CXX object core/src/core-imp/CMakeFiles/core-imp.dir/gc_user.cpp.o
/home/zk/CODA/core/src/core/protocol-percentile.cpp: In member function ‘virtual core::FHEArg PercentileProtocol::parameters() const’:
/home/zk/CODA/core/src/core/protocol-percentile.cpp:475:64: sorry, unimplemented: non-trivial designated initializers not supported
     core::FHEArg arg = { .p = 8191, .m = 16384, .r = 1, .L = 8 };
                                                                ^

**Comment by fionser** [comment]
@IkarosCoCo . It seems that for some old g++, the order of initializer should be the same
as that in the definition of FHEArgs. (i.e., here we should exchange the order of `.p` and `.m`).
I have patched this building issues, and passed the building in my machine with g++4.9.4. So I going to close this issue. Thx a lot.

**Comment by wangqi01** [comment]
Thx a lot.
